services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_URL="postgresql://postgres:0@localhost:5432/Todo?schema=public"
    volumes:
      - ./api/prisma:/prisma
